### PR TITLE
Add submodule of just cscore

### PR DESCRIPTION
**Pull request by virtuald**
@PeterJohnson, opinions? This doesn't seem that terrible, and it's a lot easier to clone?

### CODE REVIEW

**Comment by auscompgeek** [comment]
Hm. Surely a couple of `git-subtree` calls would be faster for this.

**Comment by virtuald** [comment]
Unfortunately, `git-subtree` doesn't support multiple prefixes. Given that this is only run by maintainers periodically, it doesn't seem that bad.

**Comment by virtuald** [comment]
However, if you have a faster/cleaner way of accomplishing this same thing, I'm open to it!

**Comment by auscompgeek** [comment]
My suggestion was going to be to have two subtree repos, similar to what we had before.

**Comment by virtuald** [comment]
Eh, that sounds worse.

**Pull request merged**
