### PR TITLE
Build in CI via Docker

### PR DESCRIPTION
**Pull request by auscompgeek**
Closes: #37

### CODE REVIEW

**Comment by virtuald** [comment]
Weird, why didn't this build in travis? Seems like it built under your account?

**Comment by auscompgeek** [comment]
I think PR builds are disabled on this repo.

**Comment by virtuald** [comment]
So they are. Oops. Re-enabled.

**Comment by virtuald** [comment]
I suspect if you rebase upon master it'll build this time?

**Comment by virtuald** [comment]
:shipit:

**Pull request merged**
